version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_USERNAME: rootuser
      MONGO_INITDB_PASSWORD: rootpass
    command: mongod --auth

