spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: mydatabase
            username: rootuser
            password: rootpass
            authentication-database: admin
server:
    port: 8080