spring:
    data:
        mongodb:
            uri: mongodb://root:example@localhost:27017/mydatabase
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:mysql://localhost:3306/mydatabase
        username: root
        password: example

